job_environments:
  common_environment: &common_environment
    APP_HOSTPATH: usa
    CONTAINER_PREFIX: planet4-usa
    WP_DB_NAME_PREFIX: planet4-usa_wordpress
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: usa-development
    HELM_RELEASE: planet4-usa
    WP_DB_NAME: planet4-usa_wordpress_develop
    WP_STATELESS_BUCKET: planet4-usa-stateless-develop
  release_build_env: &release_build_env
    GOOGLE_PROJECT_ID: planet4-production
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: www-stage.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: usa-staging
    HELM_RELEASE: planet4-usa-release
    WP_DB_NAME: planet4-usa_wordpress_release
    WP_STATELESS_BUCKET: planet4-usa-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: www-prod.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: usa
    HELM_RELEASE: planet4-usa-master
    MIN_REPLICA_COUNT: 2
    WP_DB_NAME: planet4-usa_wordpress_master
    WP_STATELESS_BUCKET: planet4-usa-stateless
